/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/avatar-generate`; params?: Router.UnknownInputParams; } | { pathname: `/avatar-generating`; params?: Router.UnknownInputParams; } | { pathname: `/avatar-result`; params?: Router.UnknownInputParams; } | { pathname: `/clothing-detail`; params?: Router.UnknownInputParams; } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/recommend-outfit-detail`; params?: Router.UnknownInputParams; } | { pathname: `/survey`; params?: Router.UnknownInputParams; } | { pathname: `/lookbook-detail`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/closet` | `/closet`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/profile` | `/profile`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/recommend` | `/recommend`; params?: Router.UnknownInputParams; };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/avatar-generate`; params?: Router.UnknownOutputParams; } | { pathname: `/avatar-generating`; params?: Router.UnknownOutputParams; } | { pathname: `/avatar-result`; params?: Router.UnknownOutputParams; } | { pathname: `/clothing-detail`; params?: Router.UnknownOutputParams; } | { pathname: `/`; params?: Router.UnknownOutputParams; } | { pathname: `/recommend-outfit-detail`; params?: Router.UnknownOutputParams; } | { pathname: `/survey`; params?: Router.UnknownOutputParams; } | { pathname: `/lookbook-detail`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/closet` | `/closet`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/profile` | `/profile`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/recommend` | `/recommend`; params?: Router.UnknownOutputParams; };
      href: Router.RelativePathString | Router.ExternalPathString | `/avatar-generate${`?${string}` | `#${string}` | ''}` | `/avatar-generating${`?${string}` | `#${string}` | ''}` | `/avatar-result${`?${string}` | `#${string}` | ''}` | `/clothing-detail${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | `/recommend-outfit-detail${`?${string}` | `#${string}` | ''}` | `/survey${`?${string}` | `#${string}` | ''}` | `/lookbook-detail${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/closet${`?${string}` | `#${string}` | ''}` | `/closet${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/profile${`?${string}` | `#${string}` | ''}` | `/profile${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/recommend${`?${string}` | `#${string}` | ''}` | `/recommend${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/avatar-generate`; params?: Router.UnknownInputParams; } | { pathname: `/avatar-generating`; params?: Router.UnknownInputParams; } | { pathname: `/avatar-result`; params?: Router.UnknownInputParams; } | { pathname: `/clothing-detail`; params?: Router.UnknownInputParams; } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/recommend-outfit-detail`; params?: Router.UnknownInputParams; } | { pathname: `/survey`; params?: Router.UnknownInputParams; } | { pathname: `/lookbook-detail`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/closet` | `/closet`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/profile` | `/profile`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/recommend` | `/recommend`; params?: Router.UnknownInputParams; };
    }
  }
}
